image: node:lts

services:
  - mongo

cache:
    paths:
    - dist
    - node_modules
    - coverage

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm ci
    - npm run compile

test:
  stage: test
  script:
    - cp .env-default .env
    - export MONGO_HOST=mongo
    - export MONGO_PORT=27017
    - npm run test:coverage
  artifacts:
    paths:
    - coverage

coverage:
  stage: deploy
  dependencies:
    - build
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master

.upload_template: &upload_template
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - which ssh-agent || ( apk --update add openssh-client )
    - eval $(ssh-agent -s)
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - scp -r dist/* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
    - scp -r package*.json $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
    - scp -r public $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
    # Trigger service restart
    - date > deploy-time.txt
    - scp deploy-time.txt $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_TRIGGER

upload-prod:
  <<: *upload_template
  variables:
    DEPLOY_PATH: $DEPLOY_PATH_PROD
    DEPLOY_TRIGGER: $DEPLOY_TRIGGER_PROD
  only:
    - tags

upload-preview:
  <<: *upload_template
  variables:
    DEPLOY_PATH: $DEPLOY_PATH_PREVIEW
    DEPLOY_TRIGGER: $DEPLOY_TRIGGER_PREVIEW
  only:
    refs:
      - master
