image: node:lts

services:
  - mongo

cache:
    paths:
    - dist
    - node_modules

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm ci
    - npm run compile
    - npm run test:coverage
  artifacts:
    paths:
    - coverage

test:
  stage: test
  script:
    - cp .env-default .env
    - MONGO_HOST=mongo npm run test:coverage
  artifacts:
    paths:
    - coverage

coverage:
  stage: deploy
  dependencies:
    - build
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master

.upload_template: &upload_template
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - which ssh-agent || ( apk --update add openssh-client )
    - eval $(ssh-agent -s)
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - scp  -r build/* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH

upload-prod:
  <<: *upload_template
  variables:
    DEPLOY_PATH: $DEPLOY_PATH_PROD
  only:
    - tags

upload-preview:
  <<: *upload_template
  variables:
    DEPLOY_PATH: $DEPLOY_PATH_PREVIEW
  only:
    refs:
      - master
